input: ["none"]
output: ["img", "pipeline_end", "filename", "saved_video_fps", "image_id", "coco_instance", "image_size"]

resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
mirror_image: False

type: instances
detect_class: ["all"]
images_dir: 'PeekingDuck/coco/val2017'
instances_dir: 'PeekingDuck/coco/annotations/instances_val2017.json'
keypoints_dir: 'PeekingDuck/coco/annotations/person_keypoints_val2017.json'

