input: ["all"]
output: ["avg", "min", "max"]

identity: null
conditional_count: null
length: null
minimum: null
maximum: null

# identity: count
# conditional_count: "obj_attrs['flags'] == 'TOO CLOSE!'"
# length: large_groups
# minimum: null
# maximum: obj_attrs['ids']


