input: ["all"]
output: ["avg", "min", "max"]

target: {
  data_type: null,
  get: null,
} 
apply: {
  function: identity,
  condition: {
    operator: null,
    operand: null
  }
}

# conditional_count: null
# identity: null



# data_type: obj_attrs["flags"]
# function: conditional_count, ">=", 40

# function: identity


# dabble.statistics:

#   identity: count
#   conditional_count: "obj_attrs['flags'] >= 40"

#   len: large_groups
#   max: obj_attrs["flags"]

#   get: [details->age, details->gender]

