input: ["pipeline_end"]
output: ["fps"]

fps_log_display: True   # Boolean to display logging of fps moving average
fps_log_freq: 30   # Logging frequency of FPS every n frames in cli
dampen_fps: True   # Returns average FPS if True, instantaneous if False
