nodes:
  - input.recorded:
    - input_source: "/Users/ngleeping/Downloads/running.mp4"
  - model.yolo:
    - model_type: v4
  - draw.bbox
  - output.media_writer:
    - outputdir: "/Users/ngleeping/Desktop/"
