input: ["img"]
output: ["density_map", "count"]

weights_parent_dir: null
weights:
  {
    model_subdir: csrnet,
    blob_file:
      { dense: shanghaitech-part-a.zip, sparse: shanghaitech-part-b.zip },
    model_file: { dense: shanghaitech-part-a, sparse: shanghaitech-part-b },
  }

model_type: sparse # sparse or dense
width: 640
