input: ["img"]
output: ["bboxes", "keypoints", "keypoint_scores", "keypoint_conns", "bbox_labels"]


model_type: multipose_lightning
weights_dir: ["../peekingduck_weights/movenet"]
model_weights_dir: {
    multipose_lightning: ../peekingduck_weights/movenet/multipose_lightning,
    singlepose_lightning: ../peekingduck_weights/movenet/singlepose_lightning,
    singlepose_thunder: ../peekingduck_weights/movenet/singlepose_thunder,
}
blob_file: "movenet.zip"

resolution: {
    singlepose_lightning: { height: 192, width: 192 },
    singlepose_thunder: { height: 256, width: 256 },
    multipose_lightning: { height: 256, width: 256 }, 
} # only multipose can use dynamic shape that needs be multiples of 32
  # recommended shape is 256

bbox_score_threshold: 0.2
keypoint_score_threshold: 0.2