name: Daily Drift Checks

on:
  workflow_dispatch:
  schedule:
    # run at 6am SGT
    - cron: "0 8 * * *"

jobs:
  system-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install peekingduck locally
        run: |
          python -m pip install --upgrade pip
          pip install -r cicd_requirements.txt
          TEST_VER=`grep -m 1 TEST_VERSION ./tests/api/test_api.py | cut -d ' ' -f 3`
          TEST_VER=`echo ${TEST_VER} | cut -d '"' -f 2`
          echo "test_api.py TEST_VER=${TEST_VER}"
          bash ./scripts/update_version.sh ${TEST_VER}
          pip install . --no-dependencies
      - name: Run api tests
        run: bash ./scripts/run_tests.sh api
      - name: Run system-checks
        uses: ./.github/actions/system-test # note only works after checkout@v2
